#!/bin/bash

echo 'Updating the system. Will ask for sudo password'

sudo apt update -y && sudo apt upgrade -y

# Enable zipped downloads
sudo apt install -y zip unzip php-zip

echo 'Adding ondrej/php repository to install php8.0'
sudo apt install software-properties-common
sudo add-apt-repository ppa:ondrej/php
sudo add-apt-repository ppa:ondrej/apache2
sudo apt update && sudo apt upgrade
sudo apt install php8.0 libapache2-mod-php8.0
sudo apt install php8.0-mbstring php8.0-curl php8.0-xml php8.0-intl php8.0-mysql php8.0-memcache php8.0-gd php8.0-imagick
sudo a2enmod rewrite
sudo service apache2 start

echo 'Installing MariaDB'
sudo apt install mariadb-server
sudo mysql_secure_installation

echo 'Configuring virtual hosts under /var/www/wikiclimb'
echo 'Make sure you have configured DNS'
sudo mkdir /var/www/wikiclimb
sudo ln -s ~/app/apiv1/web /var/www/wikiclimb/api
sudo ln -s ~/app/backend/web /var/www/wikiclimb/backend
sudo ln -s ~/app/frontend/web /var/www/wikiclimb/frontend
sudo cp ./helpers/apache/wikiclimb.conf /etc/apache2/sites-available/
sudo a2ensite wikiclimb.conf
sudo a2dissite 000-default.conf
sudo apache2ctl configtest

sudo 'Trying to install server certificates using LetsEncrypt'
sudo apt install certbot python3-certbot-apache

echo 'Configure Yii'
php init --env=Production --overwrite=All
echo 'Adjust DB parameters'


php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
php composer.phar install
