version: '3.9'

services:
  wkcdb:
    image: mariadb:10.6.4
    ports:
      - "33007:3306"
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=wikiclimb
      - MARIADB_USER=wikiclimb_user
      - MARIADB_PASSWORD=password
    networks:
      wkc:
        aliases:
          - wkcdb
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  wkcdbtest:
    image: mariadb:10.6.4
    ports:
      - "33006:3306"
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=wikiclimb_test
      - MARIADB_USER=wikiclimb_test_user
      - MARIADB_PASSWORD=password
    networks:
      wkc:
        aliases:
          - wkcdbtest
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  apiv1:
    build: apiv1
    ports:
      - "22080:80"
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    depends_on:
      - wkcdb
      - wkcdbtest
    networks:
      - wkc

  frontend:
    build: frontend
    ports:
      - "20080:80"
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    depends_on:
      - wkcdb
      - wkcdbtest
    networks:
      - wkc

  backend:
    build: backend
    ports:
      - "21080:80"
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    depends_on:
      - wkcdb
      - wkcdbtest
    networks:
      - wkc

networks:
  wkc:
    driver: bridge
#    attachable: true
