#!/bin/sh
# Constants
GREEN='\033[0;32m'
PURPLE='\033[0;35m'
#RED='\033[0;31m'
NC='\033[0m' # No Color
CONTAINER_NAME=wikiclimb-mariadb-container

# Start the container
printf "${GREEN}» Starting container: $CONTAINER_NAME${NC}\n"
docker run -d --name $CONTAINER_NAME -e MARIADB_ROOT_PASSWORD=password -p 33006:3306 \
 --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 mariadb

printf "${GREEN}» Checking container: $CONTAINER_NAME${NC}\n"
sleep 5
mysql --host 127.0.0.1 --port 33006 --protocol=tcp -uroot -ppassword -e "CREATE DATABASE wikiclimb_test"
mysql --host 127.0.0.1 --port 33006 --protocol=tcp -uroot -ppassword -e "SHOW DATABASES"

printf "${GREEN}» Running migrations${NC}\n"
./yii_test migrate --interactive=0

printf "${GREEN}» Running tests${NC}\n"
vendor/bin/codecept run

printf "${GREEN}» Stopping container: ${NC}"
docker stop $CONTAINER_NAME
printf "${GREEN}» Removing container: ${NC}"
docker rm $CONTAINER_NAME
printf "${GREEN}✔✔✔✔✔✔${PURPLE} ALL DONE ${GREEN}✔✔✔✔✔✔${NC}\n"
