name: Codeception Tests
on: [ push, pull_request ]
jobs:
  codecept-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Init environment
        run: php init --env=Test --overwrite=All
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress
      - name: Start services
        run: docker-compose up -d
      - name: Check containers health
        run: docker ps -a
      - name: Wait for containers
        run: sleep 10
      - name: Check containers health after delay
        run: docker ps -a
      #      - name: Verify persistent database connection from host
      #        run: |
      #          sudo apt-get install -y mysql-client
      #          mysql --host 127.0.0.1 --port 33007 --protocol=tcp -uroot -ppassword -e "SHOW DATABASES"
      #      - name: Verify test database connection from host
      #        run: mysql --host 127.0.0.1 --port 33006 --protocol=tcp -uroot -ppassword -e "SHOW DATABASES"
      - name: Migrate database
        run: ./yii_test migrate --interactive=0
      - name: Execute tests
        run: vendor/bin/codecept run
      - name: Clean up services
        run: docker-compose down
